#!/bin/bash -x

REPOREVISION=2.7.2

function repo2repo {
  docker pull $REPO/"$1":"$2"
  docker tag $REPO/"$1":"$2" localhost:5000/helm-$REPOREVISION/"$1":"$2"
  docker push localhost:5000/helm-$REPOREVISION/"$1":"$2"
}

git clone https://github.com/kfox1111/hubbuildtools

hubbuildtools/hubhookhelpers/quinesetup

export REPO=gcr.io/kubernetes-helm

repo2repo tiller v$REPOREVISION

hubbuildtools/hubhookhelpers/quinebuild
